[package]
name = "mwe"
version = "0.1.0"
authors = ["Linera <contact@linera.io>"]
edition = "2021"

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
linera-sdk.workspace = true
serde.workspace = true
serde_json.workspace = true
